FROM openjdk:13-jdk-alpine
COPY ./target/appassembler /usr/src/kprime
WORKDIR /usr/src/kprime
ENV KPRIME_GITHUB_KEY=$KPRIME_GITHUB_KEY
ENV KPRIME_GITHUB_SECRET=$KPRIME_GITHUB_SECRET
ENV KPRIME_GITLAB_KEY=$KPRIME_GITLAB_KEY
ENV KPRIME_GITLAB_SECRET=$KPRIME_GITLAB_SECRET
CMD ["bin/app"]